#!/usr/bin/env python3
"""Regenerate src/ada_logo.ads -- the 240x240 RGB565 startup splash -- from ada_logo.svg.

The committed src/ada_logo.ads (a pure-Ada package, the Pixels aggregate) is the
build input.  This script only needs to be re-run if the source art or the target
size changes.

    ./gen_ada_logo.py            # ada_logo.svg -> src/ada_logo.ads (240x240, white bg)

Requires Inkscape (to rasterise the SVG to its bounding box) and Pillow.
"""
import os
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
SVG = os.path.join(HERE, "ada_logo.svg")
OUT = os.path.join(HERE, "src", "ada_logo.ads")   # a generated Ada package (was a C header)
SIZE = 240          # square panel
MARGIN = 8          # white border, px
BG = (255, 255, 255)


def rgb565(c):
    r, g, b = c
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def main():
    from PIL import Image

    with tempfile.TemporaryDirectory() as td:
        png = os.path.join(td, "hi.png")
        #  Rasterise just the drawing (crops to the mascot's bounding box) at a
        #  generous width so the downscale antialiases cleanly.
        subprocess.run(
            ["inkscape", SVG, "--export-type=png", "--export-filename=" + png,
             "--export-area-drawing", "--export-width=900"],
            check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        im = Image.open(png).convert("RGBA")

    box = SIZE - 2 * MARGIN
    w, h = im.size
    scale = min(box / w, box / h)
    nw, nh = max(1, round(w * scale)), max(1, round(h * scale))
    im = im.resize((nw, nh), Image.LANCZOS)

    canvas = Image.new("RGBA", (SIZE, SIZE), BG + (255,))
    canvas.alpha_composite(im, ((SIZE - nw) // 2, (SIZE - nh) // 2))
    vals = [rgb565(c) for c in canvas.convert("RGB").getdata()]
    assert len(vals) == SIZE * SIZE

    lines = [
        "with ESP32S3.ST7789;",
        "",
        "--  Auto-generated by gen_ada_logo.py from ada_logo.svg -- do not edit by hand.",
        "--  %dx%d RGB565 splash (the textless Ada mascot) on a white field, blitted"
        % (SIZE, SIZE),
        "--  via ESP32S3.ST7789.Draw_Bitmap.  Pure Ada -- no C header / glue.",
        "package Ada_Logo is",
        "",
        "   Width  : constant := %d;" % SIZE,
        "   Height : constant := %d;" % SIZE,
        "",
        "   --  Row-major, one RGB565 value per pixel (the layout Draw_Bitmap expects).",
        "   Pixels : constant ESP32S3.ST7789.Color_Array (0 .. Width * Height - 1) :=",
        "     (",
    ]
    for i in range(0, len(vals), 12):
        sep = "," if i + 12 < len(vals) else ");"
        lines.append("      " + ",".join("16#%04X#" % v for v in vals[i:i + 12]) + sep)
    lines.append("")
    lines.append("end Ada_Logo;")
    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote %s (%d px placed at %dx%d, scale %.4f)"
          % (os.path.relpath(OUT), len(vals), nw, nh, scale))


if __name__ == "__main__":
    sys.exit(main())
