--  B612 anti-aliased font on an ST7789 display -- bare-metal ESP32-S3 (no
--  FreeRTOS, no IDF)
--  ==========================================================================
--  What it demonstrates
--    The panel-agnostic HAL text engine drawing the B612 typeface (Airbus's
--    cockpit font) on a real 240x240 ST7789 panel at three sizes (12 / 16 /
--    24 px), anti-aliased.  The engine is ESP32S3.Fonts (data model) +
--    ESP32S3.Fonts.Render (generic blitter), here instantiated for this driver
--    as ESP32S3.ST7789.Fonts.  Each size is an independent atlas, so a real
--    program spends flash only on the Font values it actually references; the
--    demo prints each size's footprint to prove it.
--
--    Anti-aliasing works on this write-only panel because each glyph is
--    alpha-blended against a KNOWN background (no framebuffer read-back, which
--    the panel doesn't support).
--
--  Build & run
--    ./x run esp32s3_b612          (embedded profile -- build.sh sets
--                                   ESP32S3_RTS_PROFILE=embedded)
--
--  Output
--    The panel is the real output.  The console first prints a banner and one
--    "[b612]   <size> <bytes> bytes" line per atlas; the panel then paints the
--    three sizes, a punctuation row, and a Latin-1 accent row.
--
--  Hardware (wiring)
--    SPI2 clock  SCLK     = IO12
--    SPI2 data   MOSI/SDA = IO13   (write-only -- no MISO)
--    control     DC       = IO16   (data/command select, driven by the driver)
--    control     CS       = IO10   (chip select, driven by the driver)
--    backlight   BLK      = IO6    (driven HERE by the example, NOT the driver)
--    Panel: ST7789 240x240, RGB565.
--
--    Atlas data lives in glue.c (b612_atlas.h, generated by the shared
--    tools/gen_font.py -- see regen.sh); 'with' only the sizes used, so the
--    others are never linked.
with Ada.Real_Time; use Ada.Real_Time;

with ESP32S3.GPIO;
with ESP32S3.ST7789;
with ESP32S3.Fonts;
with ESP32S3.ST7789.Fonts;
with ESP32S3.Log; use ESP32S3.Log;
--  'with' only the sizes used -- unused ones are never linked.
with B612_24;
with B612_16;
with B612_12;

with System.BB.CPU_Primitives.Multiprocessors;
pragma Unreferenced (System.BB.CPU_Primitives.Multiprocessors);

procedure Main is
   package Display renames ESP32S3.ST7789;
   package Text_Renderer renames ESP32S3.ST7789.Fonts;   --  the panel's text engine

   --  SPI2 wiring: clock, data, and the two control lines the driver toggles.
   Serial_Clock_Pin : constant ESP32S3.GPIO.Pin_Id := 12;   --  SCLK
   Data_Out_Pin     : constant ESP32S3.GPIO.Pin_Id := 13;   --  MOSI / SDA
   Data_Command_Pin : constant ESP32S3.GPIO.Pin_Id := 16;   --  DC select
   Chip_Select_Pin  : constant ESP32S3.GPIO.Pin_Id := 10;   --  CS

   --  Backlight enable -- the example's job, not the driver's.
   Backlight_Pin : constant ESP32S3.GPIO.Pin_Id := 6;

   --  The known background glyphs are blended against (black here).
   Text_Background : constant ESP32S3.Fonts.RGB := (0, 0, 0);

   Display_Device  : Display.Device;
   Display_Session : Display.Session;

   --  Report one variant's flash size over the console
   --  ("[b612]   %-8s %5d bytes").
   Size_Field_Width : constant := 8;    --  pad the size name to this column
   Byte_Count_Width : constant := 5;    --  right-justify the byte count

   procedure Show_Size (Name : String; Bytes : Integer) is
   begin
      delay until Clock + Milliseconds (25);
      Put ("[b612]   ");
      Put (Name);
      for I in Name'Length + 1 .. Size_Field_Width loop
         Put (" ");
      end loop;
      Put (" ");
      Put (Bytes, Width => Byte_Count_Width);
      Put_Line (" bytes");
   end Show_Size;

   --  Layout of the text rows on the panel.
   Left_Margin      : constant := 4;   --  x of every line's first glyph
   First_Baseline_Y : constant := 2;   --  top of the first line
   Line_Gap         : constant := 3;   --  blank pixels between lines

   --  Running top-of-line cursor; draw one line, advance by the font height.
   Cursor_Y : Integer := First_Baseline_Y;

   procedure Put_Line_On_Panel
     (A_Font : ESP32S3.Fonts.Font; Text : String; Foreground : ESP32S3.Fonts.RGB) is
   begin
      Text_Renderer.Draw_Text
        (Display_Session,
         A_Font,
         Left_Margin,
         Cursor_Y + A_Font.Ascent,
         Text,
         Foreground,
         Text_Background);
      Cursor_Y := Cursor_Y + A_Font.Height + Line_Gap;
   end Put_Line_On_Panel;

   White : constant ESP32S3.Fonts.RGB := (255, 255, 255);
   Cyan  : constant ESP32S3.Fonts.RGB := (0, 220, 255);
   Amber : constant ESP32S3.Fonts.RGB := (255, 190, 0);
begin
   delay until Clock + Milliseconds (200);   --  let the console settle
   Put_Line ("[b612] anti-aliased B612 font: 12/16/24 px -> ST7789 240x240");
   Show_Size ("12px", B612_12.Bytes);
   Show_Size ("16px", B612_16.Bytes);
   Show_Size ("24px", B612_24.Bytes);

   --  Backlight is the example's job, not the driver's: drive IO6 high.
   ESP32S3.GPIO.Configure (Backlight_Pin, Mode => ESP32S3.GPIO.Output);
   ESP32S3.GPIO.Set (Backlight_Pin);

   Display.Setup
     (Display_Device,
      Sclk => Serial_Clock_Pin,
      Mosi => Data_Out_Pin,
      DC   => Data_Command_Pin,
      CS   => Chip_Select_Pin);
   Display.Acquire (Display_Session, Display_Device);
   Display.Init (Display_Session);
   Display.Fill (Display_Session, Display.Black);

   --  Anti-aliased B612 at three sizes.
   Put_Line_On_Panel (B612_24.Font, "B612  24 px", Cyan);
   Put_Line_On_Panel (B612_16.Font, "16 px  The quick brown fox", White);
   Put_Line_On_Panel (B612_16.Font, "jumps over the lazy dog.", White);
   Put_Line_On_Panel (B612_12.Font, "12 px  The quick brown fox jumps over", Amber);
   Put_Line_On_Panel (B612_12.Font, "the lazy dog. 0123456789", Amber);

   --  Punctuation + Latin-1 accents (accents built via Character'Val so the
   --  source stays plain ASCII).
   Put_Line_On_Panel (B612_16.Font, ".,:;!?@#&()[]{}+-=/ AaQqGg", White);
   declare
      Accents : constant String :=
        (Character'Val (16#C0#),
         Character'Val (16#C9#),   --  A-grave E-acute
         Character'Val (16#D1#),
         Character'Val (16#E9#),   --  N-tilde  e-acute
         Character'Val (16#F1#),
         Character'Val (16#FC#),   --  n-tilde  u-diaeresis
         Character'Val (16#DF#),
         Character'Val (16#E7#));  --  sharp-s  c-cedilla
   begin
      Put_Line_On_Panel (B612_16.Font, "Latin-1  " & Accents, Cyan);
   end;

   loop
      delay until Clock + Seconds (3600);
   end loop;
end Main;
