--  B612 font demo on a 240x240 ST7789 panel (bare-metal ESP32-S3, no FreeRTOS,
--  no IDF).  Drives anti-aliased B612 atlases at 12 / 16 / 24 px through the
--  panel-agnostic HAL text engine (ESP32S3.Fonts.Render, here instantiated as
--  ESP32S3.ST7789.Fonts), and prints each size's flash footprint.
--
--  Atlas data lives in glue.c (main/b612_atlas.h, generated by the shared
--  tools/gen_font.py -- see main/regen.sh); each size is an independent set of
--  arrays, so a real program spends flash only on the Font values it references.
--  Anti-aliasing works on the write-only panel because glyphs are alpha-blended
--  against a KNOWN background.
--
--  Display: SPI2 SCLK=IO12 MOSI=IO13 DC=IO16 CS=IO10; backlight IO6 driven HERE.
with System;
with Interfaces.C; use Interfaces.C;
with Ada.Real_Time; use Ada.Real_Time;

with ESP32S3.GPIO;
with ESP32S3.ST7789;
with ESP32S3.Fonts;
with ESP32S3.ST7789.Fonts;
--  'with' only the sizes used -- unused ones are never linked.
with B612_24; with B612_16; with B612_12;

with System.BB.CPU_Primitives.Multiprocessors;
pragma Unreferenced (System.BB.CPU_Primitives.Multiprocessors);

procedure Main is
   package LCD renames ESP32S3.ST7789;
   package TF  renames ESP32S3.ST7789.Fonts;     --  the panel's text renderer

   procedure Banner;  pragma Import (C, Banner, "native_b612_banner");
   procedure Size_C (Name : System.Address; Bytes : int);
                     pragma Import (C, Size_C, "native_b612_size");

   Backlight : constant ESP32S3.GPIO.Pin_Id := 6;
   BG        : constant ESP32S3.Fonts.RGB := (0, 0, 0);   --  text background

   Dev : LCD.Device;
   S   : LCD.Session;

   --  Report one variant's flash size over the console.
   procedure Show_Size (Name : String; Bytes : Integer) is
      Buf : aliased String (1 .. Name'Length + 1);
   begin
      Buf (1 .. Name'Length) := Name;
      Buf (Buf'Last) := Character'Val (0);
      delay until Clock + Milliseconds (25);
      Size_C (Buf'Address, int (Bytes));
   end Show_Size;

   --  Running top-of-line cursor; draw one line, advance by the font height.
   Y : Integer := 2;
   procedure Put (F : ESP32S3.Fonts.Font; Str : String; FG : ESP32S3.Fonts.RGB)
   is
   begin
      TF.Draw_Text (S, F, 4, Y + F.Ascent, Str, FG, BG);
      Y := Y + F.Height + 3;
   end Put;

   White : constant ESP32S3.Fonts.RGB := (255, 255, 255);
   Cyan  : constant ESP32S3.Fonts.RGB := (0, 220, 255);
   Amber : constant ESP32S3.Fonts.RGB := (255, 190, 0);
begin
   delay until Clock + Milliseconds (200);
   Banner;
   Show_Size ("12px", B612_12.Bytes);
   Show_Size ("16px", B612_16.Bytes);
   Show_Size ("24px", B612_24.Bytes);

   ESP32S3.GPIO.Configure (Backlight, Mode => ESP32S3.GPIO.Output);
   ESP32S3.GPIO.Set (Backlight);

   LCD.Setup (Dev, Sclk => 12, Mosi => 13, DC => 16, CS => 10);
   LCD.Acquire (S, Dev);
   LCD.Init (S);
   LCD.Fill (S, LCD.Black);

   --  Anti-aliased B612 at three sizes.
   Put (B612_24.Font, "B612  24 px",                  Cyan);
   Put (B612_16.Font, "16 px  The quick brown fox",   White);
   Put (B612_16.Font, "jumps over the lazy dog.",     White);
   Put (B612_12.Font, "12 px  The quick brown fox jumps over", Amber);
   Put (B612_12.Font, "the lazy dog. 0123456789",     Amber);

   --  Punctuation + Latin-1 accents (accents built via Character'Val so the
   --  source stays plain ASCII).
   Put (B612_16.Font, ".,:;!?@#&()[]{}+-=/ AaQqGg",  White);
   declare
      Accents : constant String :=
        (Character'Val (16#C0#), Character'Val (16#C9#),   --  A-grave E-acute
         Character'Val (16#D1#), Character'Val (16#E9#),   --  N-tilde  e-acute
         Character'Val (16#F1#), Character'Val (16#FC#),   --  n-tilde  u-diaeresis
         Character'Val (16#DF#), Character'Val (16#E7#));  --  sharp-s  c-cedilla
   begin
      Put (B612_16.Font, "Latin-1  " & Accents, Cyan);
   end;

   loop
      delay until Clock + Seconds (3600);
   end loop;
end Main;
