--  Native known-answer test for P384.Verify against a real ECDSA-P384-SHA384
--  signature (generated by openssl; regenerate with the script in the commit).
with Ada.Text_IO; use Ada.Text_IO;
with Interfaces; use Interfaces;
with P384;

procedure P384_Host is
   Passed, Failed : Natural := 0;
   procedure Check (Label : String; Ok : Boolean) is
   begin
      if Ok then Passed := Passed + 1; Put_Line ("  ok   " & Label);
      else Failed := Failed + 1; Put_Line ("  FAIL " & Label); end if;
   end Check;

   KAT_X : constant P384.Bytes_48 :=
     (16#E4#, 16#58#, 16#86#, 16#31#, 16#36#, 16#49#, 16#41#, 16#12#, 16#FA#, 16#50#, 16#11#, 16#96#, 16#67#, 16#FA#, 16#35#, 16#85#, 16#83#, 16#1D#, 16#76#, 16#B4#, 16#D6#, 16#9B#, 16#75#, 16#68#, 16#04#, 16#E7#, 16#0B#, 16#A0#, 16#3A#, 16#F3#, 16#13#, 16#DF#, 16#4D#, 16#69#, 16#89#, 16#EB#, 16#CE#, 16#F6#, 16#B4#, 16#7B#, 16#3C#, 16#51#, 16#24#, 16#5C#, 16#26#, 16#A7#, 16#CA#, 16#BE#);
   KAT_Y : constant P384.Bytes_48 :=
     (16#2F#, 16#D2#, 16#FF#, 16#09#, 16#DF#, 16#97#, 16#53#, 16#6D#, 16#3E#, 16#CA#, 16#B7#, 16#B1#, 16#ED#, 16#13#, 16#00#, 16#68#, 16#18#, 16#9F#, 16#B6#, 16#63#, 16#D7#, 16#97#, 16#DD#, 16#17#, 16#19#, 16#01#, 16#7B#, 16#C8#, 16#01#, 16#04#, 16#0F#, 16#7E#, 16#62#, 16#03#, 16#52#, 16#EE#, 16#9E#, 16#A1#, 16#1A#, 16#AB#, 16#5A#, 16#F0#, 16#02#, 16#E3#, 16#BC#, 16#2D#, 16#40#, 16#DA#);
   KAT_H : constant P384.Bytes_48 :=
     (16#A9#, 16#46#, 16#28#, 16#9B#, 16#15#, 16#EA#, 16#B6#, 16#7E#, 16#33#, 16#32#, 16#07#, 16#2C#, 16#15#, 16#5C#, 16#21#, 16#B4#, 16#54#, 16#40#, 16#86#, 16#5B#, 16#E9#, 16#0C#, 16#93#, 16#27#, 16#4A#, 16#93#, 16#B9#, 16#F2#, 16#1F#, 16#C8#, 16#A5#, 16#D0#, 16#55#, 16#F1#, 16#CB#, 16#2C#, 16#9B#, 16#69#, 16#81#, 16#2E#, 16#9C#, 16#46#, 16#ED#, 16#9E#, 16#0F#, 16#CD#, 16#8A#, 16#7B#);
   KAT_R : constant P384.Bytes_48 :=
     (16#FC#, 16#A6#, 16#15#, 16#0B#, 16#1D#, 16#11#, 16#0E#, 16#3F#, 16#F1#, 16#89#, 16#72#, 16#AF#, 16#63#, 16#EB#, 16#5C#, 16#7A#, 16#22#, 16#3A#, 16#7A#, 16#F3#, 16#24#, 16#F4#, 16#51#, 16#D3#, 16#A5#, 16#03#, 16#3C#, 16#56#, 16#6F#, 16#C5#, 16#49#, 16#AD#, 16#CC#, 16#05#, 16#F4#, 16#62#, 16#3E#, 16#BB#, 16#71#, 16#0B#, 16#49#, 16#B1#, 16#96#, 16#D3#, 16#61#, 16#69#, 16#89#, 16#00#);
   KAT_S : constant P384.Bytes_48 :=
     (16#FE#, 16#67#, 16#22#, 16#FD#, 16#28#, 16#59#, 16#A6#, 16#F5#, 16#17#, 16#16#, 16#8B#, 16#1C#, 16#D1#, 16#5D#, 16#59#, 16#46#, 16#E1#, 16#68#, 16#6E#, 16#5B#, 16#CE#, 16#C1#, 16#96#, 16#59#, 16#F8#, 16#5A#, 16#10#, 16#1B#, 16#DC#, 16#09#, 16#7F#, 16#FD#, 16#5E#, 16#64#, 16#FA#, 16#AB#, 16#B9#, 16#3D#, 16#21#, 16#14#, 16#C7#, 16#5C#, 16#AD#, 16#98#, 16#72#, 16#40#, 16#72#, 16#7B#);

   Bad_R : P384.Bytes_48 := KAT_R;
   Bad_H : P384.Bytes_48 := KAT_H;
begin
   Check ("valid signature verifies",
          P384.Verify (KAT_X, KAT_Y, KAT_H, KAT_R, KAT_S));

   Bad_R (47) := Bad_R (47) xor 1;
   Check ("tampered r rejected",
          not P384.Verify (KAT_X, KAT_Y, KAT_H, Bad_R, KAT_S));

   Bad_H (0) := Bad_H (0) xor 16#80#;
   Check ("wrong message rejected",
          not P384.Verify (KAT_X, KAT_Y, Bad_H, KAT_R, KAT_S));

   Check ("swapped X/Y rejected",
          not P384.Verify (KAT_Y, KAT_X, KAT_H, KAT_R, KAT_S));

   Put_Line ("P384:" & Natural'Image (Passed) & " passed,"
             & Natural'Image (Failed) & " failed");
   if Failed > 0 then raise Program_Error; end if;
end P384_Host;
