#!/usr/bin/env python3
"""Rasterise a TrueType/OpenType font into glyph atlases for ESP32S3.Fonts.

Font-agnostic: point it at any .ttf/.otf, pick sizes / a code range / encoding,
and it emits, per size, a C header of flat parallel arrays (compiled into an
example's glue.c) and a one-line Ada package exposing an ESP32S3.Fonts.Font.
It also emits <name>_atlas.h, an aggregator that #includes every size.

Each size's data is independent (its own C symbols / -fdata-sections section and
its own Ada package), so a program links a size only if it #includes that header
and 'with's that package -- unused sizes cost zero flash.  Font values are
panel-independent and work with any ESP32S3.Fonts.Render instantiation.

  --bpp 4   anti-aliased: 4-bit (16-level) coverage, 2 px/byte
  --bpp 1   monochrome:   1-bit coverage, 8 px/byte, ~4x smaller

Example:
  gen_font.py --ttf B612-Regular.ttf --name b612 --sizes 12,16,24 \
              --range 0x20-0xFF --bpp 4 \
              --header-dir ../examples/esp32s3_b612/main \
              --ada-dir    ../examples/esp32s3_b612/src

Requires Pillow built with FreeType.  Re-run only when the font / sizes / range /
encoding change; the committed headers + Ada packages are the build inputs.
"""
import argparse
import os
from PIL import Image, ImageFont, ImageDraw


def rasterise(ttf, size, first, last):
    font = ImageFont.truetype(ttf, size)
    ascent, descent = font.getmetrics()
    line_h = ascent + descent
    glyphs = []
    for code in range(first, last + 1):
        ch = chr(code)
        adv = round(font.getlength(ch))
        # 0x7F..0x9F (DEL + C1 controls) are not printable -- force blank.
        if 0x7F <= code <= 0x9F:
            glyphs.append(dict(adv=adv, w=0, h=0, xoff=0, yoff=0, mask=None))
            continue
        pad, base = 8, ascent + 6
        canvas = Image.new("L", (size * 3 + 2 * pad, line_h + 2 * pad), 0)
        ImageDraw.Draw(canvas).text((pad, base), ch, font=font, fill=255, anchor="ls")
        bbox = canvas.getbbox()
        if bbox is None:
            glyphs.append(dict(adv=adv, w=0, h=0, xoff=0, yoff=0, mask=None))
            continue
        l, t, r, b = bbox
        glyphs.append(dict(adv=adv, w=r - l, h=b - t, xoff=l - pad, yoff=t - base,
                           mask=list(canvas.crop(bbox).getdata())))
    return ascent, line_h, glyphs


def pack(glyphs, bpp):
    bits = bytearray()
    for g in glyphs:
        g["off"] = len(bits)
        if g["mask"] is None:
            continue
        m = g["mask"]
        if bpp == 4:                            # 2 px/byte
            for i in range(0, len(m), 2):
                hi = m[i] >> 4
                lo = (m[i + 1] >> 4) if i + 1 < len(m) else 0
                bits.append((hi << 4) | lo)
        else:                                   # 1 px/bit, 8 px/byte, MSB first
            acc = pos = 0
            for v in m:
                acc = (acc << 1) | (1 if v >= 128 else 0)
                pos += 1
                if pos == 8:
                    bits.append(acc); acc = pos = 0
            if pos:
                bits.append(acc << (8 - pos))
    return bits


def carr(name, vals, ctype, perline=24):
    out = [f"const {ctype} {name}[{len(vals)}] = {{"]
    for i in range(0, len(vals), perline):
        out.append("  " + ",".join(str(v) for v in vals[i:i + perline]) + ",")
    out.append("};")
    return "\n".join(out)


def emit_c(path, tag, font_name, bpp, first, last, glyphs, bits):
    enc = "anti-aliased 4-bit" if bpp == 4 else "monochrome 1-bit"
    L = [f"/* Auto-generated by gen_font.py from {font_name}.  variant '{tag}',",
         f"   {enc}, codes 0x{first:02X}..0x{last:02X}.  Do not edit. */",
         carr(f"{tag}_adv",  [g["adv"]  for g in glyphs], "unsigned char"),
         carr(f"{tag}_w",    [g["w"]    for g in glyphs], "unsigned char"),
         carr(f"{tag}_h",    [g["h"]    for g in glyphs], "unsigned char"),
         carr(f"{tag}_xoff", [g["xoff"] for g in glyphs], "signed char"),
         carr(f"{tag}_yoff", [g["yoff"] for g in glyphs], "signed char"),
         carr(f"{tag}_off",  [g["off"]  for g in glyphs], "unsigned short", 16),
         carr(f"{tag}_bits", list(bits), "unsigned char"),
         f"const int {tag}_len = (int) sizeof({tag}_bits);"]
    open(path, "w").write("\n".join(L) + "\n")


def emit_ada(path, pkg, tag, size, bpp, first, count, ascent, line_h, nbytes):
    enc = "anti-aliased (4-bit)" if bpp == 4 else "monochrome (1-bit)"
    A = [f"--  Auto-generated by gen_font.py -- do not edit.  One font atlas size:",
         f"--  {size} px, {enc}, {count} glyphs ({nbytes} bytes).  The arrays are",
         f"--  defined in glue.c via #include \"{tag}.h\".  'with' this package only if",
         f"--  you use this size -- otherwise its data is never linked.",
         "with ESP32S3.Fonts; use ESP32S3.Fonts;",
         "with System;",
         "",
         f"package {pkg} is",
         f"   {tag}_adv  : constant Byte_Array (0 .. {count - 1});  pragma Import (C, {tag}_adv,  \"{tag}_adv\");",
         f"   {tag}_w    : constant Byte_Array (0 .. {count - 1});  pragma Import (C, {tag}_w,    \"{tag}_w\");",
         f"   {tag}_h    : constant Byte_Array (0 .. {count - 1});  pragma Import (C, {tag}_h,    \"{tag}_h\");",
         f"   {tag}_xoff : constant SByte_Array (0 .. {count - 1}); pragma Import (C, {tag}_xoff, \"{tag}_xoff\");",
         f"   {tag}_yoff : constant SByte_Array (0 .. {count - 1}); pragma Import (C, {tag}_yoff, \"{tag}_yoff\");",
         f"   {tag}_off  : constant U16_Array (0 .. {count - 1});   pragma Import (C, {tag}_off,  \"{tag}_off\");",
         f"   {tag}_bits : constant Byte_Array (0 .. {nbytes - 1}); pragma Import (C, {tag}_bits, \"{tag}_bits\");",
         f"   Font : constant ESP32S3.Fonts.Font :=",
         f"     (First => {first}, Count => {count}, Height => {line_h}, Ascent => {ascent}, Bpp => {bpp},",
         f"      Adv  => {tag}_adv'Address,  W    => {tag}_w'Address,    H    => {tag}_h'Address,",
         f"      XOff => {tag}_xoff'Address, YOff => {tag}_yoff'Address, Off  => {tag}_off'Address,",
         f"      Bits => {tag}_bits'Address);",
         f"   Bytes : constant := {nbytes};",
         f"end {pkg};"]
    open(path, "w").write("\n".join(A) + "\n")


def main():
    ap = argparse.ArgumentParser(description="Generate ESP32S3.Fonts atlases from a TTF/OTF.")
    ap.add_argument("--ttf", required=True)
    ap.add_argument("--name", required=True, help="symbol/file prefix, e.g. b612")
    ap.add_argument("--sizes", required=True, help="comma list, e.g. 12,16,24")
    ap.add_argument("--range", default="0x20-0xFF", help="CODELO-CODEHI, e.g. 0x20-0xFF")
    ap.add_argument("--bpp", type=int, choices=(1, 4), default=4)
    ap.add_argument("--header-dir", required=True)
    ap.add_argument("--ada-dir", required=True)
    a = ap.parse_args()

    lo, hi = (int(x, 0) for x in a.range.split("-"))
    count = hi - lo + 1
    sizes = [int(s) for s in a.sizes.split(",")]
    fname = os.path.basename(a.ttf)
    tags = []
    for size in sizes:
        ascent, line_h, glyphs = rasterise(a.ttf, size, lo, hi)
        bits = pack(glyphs, a.bpp)
        tag = f"{a.name}_{size}"
        emit_c(os.path.join(a.header_dir, f"{tag}.h"),
               tag, fname, a.bpp, lo, hi, glyphs, bits)
        emit_ada(os.path.join(a.ada_dir, f"{tag}.ads"),
                 f"{a.name.capitalize()}_{size}", tag, size, a.bpp, lo, count,
                 ascent, line_h, len(bits))
        tags.append(tag)
        print(f"{tag}: {count} glyphs, {len(bits):6d} bytes  (ascent {ascent}, line {line_h})")

    inc = [f"/* Auto-generated: every {a.name} size.  For a demo that shows them all --",
           "   a real app #includes just the sizes it uses, so the rest aren't compiled. */"]
    inc += [f'#include "{t}.h"' for t in tags]
    open(os.path.join(a.header_dir, f"{a.name}_atlas.h"), "w").write("\n".join(inc) + "\n")
    print(f"wrote {a.name}_atlas.h and {len(tags)} Ada package(s)")


if __name__ == "__main__":
    main()
