#!/usr/bin/env python3
"""Rasterise a TrueType/OpenType font into glyph atlases for ESP32S3.Fonts.

Font-agnostic: point it at any .ttf/.otf, pick sizes / a code range / encoding,
and it emits, per size, one pure-Ada package: the glyph metrics + packed bitmap
as Ada constant arrays plus an ESP32S3.Fonts.Font over them.  No C header / glue.

Each size's data is its own Ada package (compiled with -fdata-sections), so a
program links a size only if it 'with's that package -- unused sizes cost zero
flash.  Font values are panel-independent and work with any ESP32S3.Fonts.Render
instantiation.

  --bpp 4   anti-aliased: 4-bit (16-level) coverage, 2 px/byte
  --bpp 1   monochrome:   1-bit coverage, 8 px/byte, ~4x smaller

Example:
  gen_font.py --ttf B612-Regular.ttf --name b612 --sizes 12,16,24 \
              --range 0x20-0xFF --bpp 4 \
              --ada-dir ../examples/esp32s3_b612/src

Requires Pillow built with FreeType.  Re-run only when the font / sizes / range /
encoding change; the committed Ada packages are the build inputs.
"""
import argparse
import os
from PIL import Image, ImageFont, ImageDraw


def rasterise(ttf, size, first, last):
    font = ImageFont.truetype(ttf, size)
    ascent, descent = font.getmetrics()
    line_h = ascent + descent
    glyphs = []
    for code in range(first, last + 1):
        ch = chr(code)
        adv = round(font.getlength(ch))
        # 0x7F..0x9F (DEL + C1 controls) are not printable -- force blank.
        if 0x7F <= code <= 0x9F:
            glyphs.append(dict(adv=adv, w=0, h=0, xoff=0, yoff=0, mask=None))
            continue
        pad, base = 8, ascent + 6
        canvas = Image.new("L", (size * 3 + 2 * pad, line_h + 2 * pad), 0)
        ImageDraw.Draw(canvas).text((pad, base), ch, font=font, fill=255, anchor="ls")
        bbox = canvas.getbbox()
        if bbox is None:
            glyphs.append(dict(adv=adv, w=0, h=0, xoff=0, yoff=0, mask=None))
            continue
        l, t, r, b = bbox
        glyphs.append(dict(adv=adv, w=r - l, h=b - t, xoff=l - pad, yoff=t - base,
                           mask=list(canvas.crop(bbox).getdata())))
    return ascent, line_h, glyphs


def pack(glyphs, bpp):
    bits = bytearray()
    for g in glyphs:
        g["off"] = len(bits)
        if g["mask"] is None:
            continue
        m = g["mask"]
        if bpp == 4:                            # 2 px/byte
            for i in range(0, len(m), 2):
                hi = m[i] >> 4
                lo = (m[i + 1] >> 4) if i + 1 < len(m) else 0
                bits.append((hi << 4) | lo)
        else:                                   # 1 px/bit, 8 px/byte, MSB first
            acc = pos = 0
            for v in m:
                acc = (acc << 1) | (1 if v >= 128 else 0)
                pos += 1
                if pos == 8:
                    bits.append(acc); acc = pos = 0
            if pos:
                bits.append(acc << (8 - pos))
    return bits


def aarr(name, vals, atype, perline=24):
    #  An Ada `constant ATYPE (0 .. N-1) := (v, v, ...)` aggregate, values wrapped
    #  PERLINE per line.  A large scalar aggregate compiles fast (~0.5 s for 57k).
    n = len(vals)
    chunks = [",".join(str(v) for v in vals[i:i + perline]) for i in range(0, n, perline)]
    body = ",\n      ".join(chunks)
    return f"   {name} : constant {atype} (0 .. {n - 1}) :=\n     ({body});"


def emit_ada(path, pkg, tag, font_name, size, bpp, first, count, ascent, line_h, glyphs, bits):
    enc = "anti-aliased (4-bit)" if bpp == 4 else "monochrome (1-bit)"
    nbytes = len(bits)
    A = [f"--  Auto-generated by gen_font.py from {font_name} -- do not edit.  One font",
         f"--  atlas size: {size} px, {enc}, {count} glyphs ({nbytes} bytes).  Pure Ada",
         f"--  data -- no C header / glue.  'with' this package only if you use this size",
         f"--  -- otherwise its data is never linked.",
         "with ESP32S3.Fonts; use ESP32S3.Fonts;",
         "with Interfaces;  use type Interfaces.Integer_8;   --  unary minus in the signed xoff/yoff",
         "with System;",
         "",
         f"package {pkg} is",
         aarr(f"{tag}_adv",  [g["adv"]  for g in glyphs], "Byte_Array"),
         aarr(f"{tag}_w",    [g["w"]    for g in glyphs], "Byte_Array"),
         aarr(f"{tag}_h",    [g["h"]    for g in glyphs], "Byte_Array"),
         aarr(f"{tag}_xoff", [g["xoff"] for g in glyphs], "SByte_Array"),
         aarr(f"{tag}_yoff", [g["yoff"] for g in glyphs], "SByte_Array"),
         aarr(f"{tag}_off",  [g["off"]  for g in glyphs], "U16_Array", 16),
         aarr(f"{tag}_bits", list(bits), "Byte_Array"),
         f"   Font : constant ESP32S3.Fonts.Font :=",
         f"     (First => {first}, Count => {count}, Height => {line_h}, Ascent => {ascent}, Bpp => {bpp},",
         f"      Adv  => {tag}_adv'Address,  W    => {tag}_w'Address,    H    => {tag}_h'Address,",
         f"      XOff => {tag}_xoff'Address, YOff => {tag}_yoff'Address, Off  => {tag}_off'Address,",
         f"      Bits => {tag}_bits'Address);",
         f"   Bytes : constant := {nbytes};",
         f"end {pkg};"]
    open(path, "w").write("\n".join(A) + "\n")


def main():
    ap = argparse.ArgumentParser(description="Generate ESP32S3.Fonts atlases from a TTF/OTF.")
    ap.add_argument("--ttf", required=True)
    ap.add_argument("--name", required=True, help="symbol/file prefix, e.g. b612")
    ap.add_argument("--sizes", required=True, help="comma list, e.g. 12,16,24")
    ap.add_argument("--range", default="0x20-0xFF", help="CODELO-CODEHI, e.g. 0x20-0xFF")
    ap.add_argument("--bpp", type=int, choices=(1, 4), default=4)
    ap.add_argument("--ada-dir", required=True, help="output dir for the generated Ada packages")
    a = ap.parse_args()

    lo, hi = (int(x, 0) for x in a.range.split("-"))
    count = hi - lo + 1
    sizes = [int(s) for s in a.sizes.split(",")]
    fname = os.path.basename(a.ttf)
    for size in sizes:
        ascent, line_h, glyphs = rasterise(a.ttf, size, lo, hi)
        bits = pack(glyphs, a.bpp)
        tag = f"{a.name}_{size}"
        emit_ada(os.path.join(a.ada_dir, f"{tag}.ads"),
                 f"{a.name.capitalize()}_{size}", tag, fname, size, a.bpp, lo, count,
                 ascent, line_h, glyphs, bits)
        print(f"{tag}: {count} glyphs, {len(bits):6d} bytes  (ascent {ascent}, line {line_h})")

    print(f"wrote {len(sizes)} Ada font package(s) to {a.ada_dir}")


if __name__ == "__main__":
    main()
