#!/bin/bash
# Regenerate src/flash_image.ads: a minimal read-only ext4 image embedded SPARSELY
# (only its non-zero 512-byte sectors).  Needs mkfs.ext4 + debugfs (e2fsprogs)
# and python3.  Run from this directory.
set -e
HERE="$(cd "$(dirname "$0")" && pwd)"
cd "$HERE"
export PATH="/usr/sbin:/sbin:$PATH"

IMG="$(mktemp /tmp/ext4flash.XXXXXX.img)"
trap 'rm -f "$IMG" /tmp/hello.txt /tmp/readme.txt' EXIT

# 256 KB, 4 KB blocks, NO journal / NO metadata_csum (the pure-Ada FS reads this).
truncate -s 256K "$IMG"
mkfs.ext4 -q -F -b 4096 -O ^has_journal,^metadata_csum -I 256 -m 0 -L ADAFLASH "$IMG"

printf 'hello from pure-Ada ext4 on wear-leveled SPI NOR flash!\n' > /tmp/hello.txt
printf 'This file lives in a real ext4 image installed on a W25Q256FV\nover the Block_Dev.WL wear-leveling FTL, read by ESP32S3.Ext4.\n' > /tmp/readme.txt
debugfs -w "$IMG" >/dev/null 2>&1 <<EOF
mkdir /docs
write /tmp/hello.txt hello.txt
write /tmp/readme.txt /docs/readme.txt
EOF

python3 - "$IMG" > src/flash_image.ads <<'PY'
import sys
data = open(sys.argv[1], 'rb').read(); sec = 512; n = len(data) // sec
nz = [i for i in range(n) if any(data[i*sec:(i+1)*sec])]
w = sys.stdout.write
w("--  GENERATED by gen_image.sh -- do not edit by hand.\n")
w("--  A minimal read-only ext4 image (4 KB blocks, no journal, no metadata_csum)\n")
w("--  holding /hello.txt and /docs/readme.txt, stored SPARSELY: only its non-zero\n")
w("--  512-byte sectors are embedded; every other filesystem sector is written\n")
w("--  back as zeros at install time.\n")
w("with Interfaces;\n\npackage Flash_Image is\n\n")
w(f"   FS_Sectors : constant := {n};   --  total 512-byte sectors of the filesystem\n")
w(f"   N_Stored   : constant := {len(nz)};   --  non-zero sectors embedded below\n\n")
w("   --  Filesystem sector index of each stored (non-zero) sector, ascending.\n")
w("   Indices : constant array (0 .. N_Stored - 1) of Natural :=\n     (")
w(", ".join(str(i) for i in nz)); w(");\n\n")
w("   --  Their bytes, concatenated: stored sector k = Blob (k*512 .. k*512+511).\n")
w("   Blob : constant array (0 .. N_Stored * 512 - 1) of Interfaces.Unsigned_8 :=\n     (")
vals = []
for i in nz:
    vals.extend(data[i*sec:(i+1)*sec])
parts = [str(b) for b in vals]
w(",\n      ".join(", ".join(parts[p:p+16]) for p in range(0, len(parts), 16)))
w(");\n\nend Flash_Image;\n")
PY
echo "wrote src/flash_image.ads ($(grep -c , src/flash_image.ads) data lines)"
