with Interfaces;              use Interfaces;
with System;                  use System;
with System.Storage_Elements; use System.Storage_Elements;
with Board_Cfg;   --  generated by build.sh from board.ads (Psram_Pages)

package body Boot_Psram is

   --  ---- direct MMIO -------------------------------------------------------
   procedure Poke (Addr, Val : Unsigned_32) is
      R : Unsigned_32
        with Import, Volatile, Address => To_Address (Integer_Address (Addr));
   begin
      R := Val;
   end Poke;

   function Peek (Addr : Unsigned_32) return Unsigned_32 is
      R : Unsigned_32
        with Import, Volatile, Address => To_Address (Integer_Address (Addr));
   begin
      return R;
   end Peek;

   --  ---- ROM imports (ROM, not blobs) --------------------------------------
   --  esp_rom_opiflash_exec_cmd(spi, mode, cmd, cmd_bits, addr, addr_bits,
   --    dummy_bits, mosi, mosi_bits, miso, miso_bits, cs_mask, is_write_erase)
   procedure Opi_Exec
     (Spi, Mode : Integer; Cmd : Unsigned_32; Cmd_Bits : Integer;
      Addr : Unsigned_32; Addr_Bits, Dummy_Bits : Integer;
      Mosi : Address; Mosi_Bits : Integer;
      Miso : Address; Miso_Bits : Integer;
      Cs_Mask : Unsigned_32; Is_Write_Erase : Integer)
     with Import, Convention => C, External_Name => "esp_rom_opiflash_exec_cmd";

   procedure Opi_Pin_Config
     with Import, Convention => C, External_Name => "esp_rom_opiflash_pin_config";
   procedure Spi_Set_Dtr_Swap (Spi, Wr, Rd : Integer)
     with Import, Convention => C, External_Name => "esp_rom_spi_set_dtr_swap_mode";
   procedure Cache_Resume_DCache (Autoload : Unsigned_32)
     with Import, Convention => C, External_Name => "Cache_Resume_DCache";
   procedure Cache_Disable_DCache
     with Import, Convention => C, External_Name => "Cache_Disable_DCache";
   procedure Cache_Enable_DCache (Autoload : Unsigned_32)
     with Import, Convention => C, External_Name => "Cache_Enable_DCache";
   function Cache_Dbus_MMU_Set
     (Ext_Ram, Vaddr, Paddr, Psize, Num, Fixed : Unsigned_32) return Integer
     with Import, Convention => C, External_Name => "Cache_Dbus_MMU_Set";

   --  ROM console (variadic; declare the fixed arities we use).
   function P1 (F : Address; A : Unsigned_32) return Integer
     with Import, Convention => C, External_Name => "esp_rom_printf";
   function P2 (F : Address; A, B : Unsigned_32) return Integer
     with Import, Convention => C, External_Name => "esp_rom_printf";
   function P4 (F : Address; A, B, C, D : Unsigned_32) return Integer
     with Import, Convention => C, External_Name => "esp_rom_printf";
   function P6 (F : Address; A, B, C, D, E, G : Unsigned_32) return Integer
     with Import, Convention => C, External_Name => "esp_rom_printf";
   Ign : Integer;

   --  ---- constants (register addresses + values, from the C / golden state) --
   Opi_Dtr : constant Integer := 7;             --  ESP_ROM_SPIFLASH_OPI_DTR_MODE
   Cs1     : constant Unsigned_32 := 2;         --  BIT(1) = the PSRAM chip select

   Clk_Div4 : constant Unsigned_32 := 16#0003_0103#;   --  /4 -> 20 MHz (low speed)
   Clk_Div2 : constant Unsigned_32 := 16#0001_0001#;   --  /2 -> 80 MHz (high speed)
   Din_Mode_1    : constant Unsigned_32 := 16#0124_9249#;  --  din=mode1 x9 lanes
   Timing_Cali_2 : constant Unsigned_32 := 16#0000_000B#;  --  CLK_ENA|CALI|EXTRA_DUMMY=2

   Spi0_Core_Clk       : constant := 16#6000_30EC#;
   Spi0_Flash_Clk      : constant := 16#6000_3014#;
   Spi1_Flash_Clk      : constant := 16#6000_2014#;
   Spi0_Sram_Clk       : constant := 16#6000_3050#;
   Spi0_Smem_Din_Mode  : constant := 16#6000_30C0#;
   Spi0_Smem_Din_Num   : constant := 16#6000_30C4#;
   Spi0_Smem_Cali      : constant := 16#6000_30BC#;
   Spi0_Mem_Date       : constant := 16#6000_33FC#;
   Spi1_Smem_Din_Mode  : constant := 16#6000_20C0#;

   --  octal MSPI data/DQS pads bumped to FUN_DRV=3 (GPIO27,28,31..37).
   Drive_Pins : constant array (0 .. 8) of Unsigned_32 :=
     (16#6000_9070#, 16#6000_9074#, 16#6000_9080#, 16#6000_9084#, 16#6000_9088#,
      16#6000_908C#, 16#6000_9090#, 16#6000_9094#, 16#6000_9098#);

   S_Psram_Size : Unsigned_32 := 0;   --  decoded from the density mode register

   --  ---- MSPI timing (was mspi_timing_src.c) -------------------------------
   procedure Set_Pin_Drive is
   begin
      Poke (Spi0_Mem_Date, 16#0210_105F#);   --  SMEM SPICLK pad drive
      for A of Drive_Pins loop
         Poke (A, (Peek (A) and not Shift_Left (Unsigned_32 (3), 10))
                  or Shift_Left (Unsigned_32 (3), 10));
      end loop;
   end Set_Pin_Drive;

   procedure Enter_Low_Speed is   --  core 80 MHz, flash+PSRAM /4 (20 MHz), din clear
   begin
      Poke (Spi0_Core_Clk, Peek (Spi0_Core_Clk) and not 3);   --  core 80 MHz
      Poke (Spi0_Flash_Clk, Clk_Div4);
      Poke (Spi1_Flash_Clk, Clk_Div4);
      Poke (Spi0_Sram_Clk,  Clk_Div4);
      Poke (Spi0_Smem_Din_Mode, 0);
      Poke (Spi0_Smem_Din_Num,  0);
      Poke (Spi0_Smem_Cali,     0);
   end Enter_Low_Speed;

   procedure Enter_High_Speed is  --  core 160 MHz, flash+PSRAM /2 (80 MHz), din=mode1
   begin
      Poke (Spi0_Core_Clk, (Peek (Spi0_Core_Clk) and not 3) or 2);   --  core 160 MHz
      Poke (Spi0_Flash_Clk, Clk_Div2);
      Poke (Spi1_Flash_Clk, Clk_Div2);
      Poke (Spi0_Sram_Clk,  Clk_Div2);
      Poke (Spi0_Smem_Cali,     Timing_Cali_2);
      Poke (Spi0_Smem_Din_Mode, Din_Mode_1);
      Poke (Spi0_Smem_Din_Num,  0);
   end Enter_High_Speed;

   --  ---- chip bring-up (was psram_impl_src.c) ------------------------------
   --  read an octal-PSRAM mode register (16-bit read returns MRn|MR(n+1)<<8).
   function Read_Mr (Addr : Unsigned_32; Bits : Integer) return Unsigned_32 is
      B : array (0 .. 1) of Unsigned_8 := (0, 0);
   begin
      Opi_Exec (1, Opi_Dtr, 16#4040#, 16, Addr, 32, 8,
                Null_Address, 0, B'Address, Bits, Cs1, 0);
      return Unsigned_32 (B (0)) or Shift_Left (Unsigned_32 (B (1)), 8);
   end Read_Mr;

   procedure Report is
      R01 : constant Unsigned_32 := Read_Mr (16#0#, 16);
      R23 : constant Unsigned_32 := Read_Mr (16#2#, 16);
      Mr4 : constant Unsigned_32 := Read_Mr (16#4#, 8);
      Mr8 : constant Unsigned_32 := Read_Mr (16#8#, 8);
      Mr0 : constant Unsigned_32 := R01 and 16#FF#;
      Mr1 : constant Unsigned_32 := Shift_Right (R01, 8) and 16#FF#;
      Mr2 : constant Unsigned_32 := R23 and 16#FF#;
      Mr3 : constant Unsigned_32 := Shift_Right (R23, 8) and 16#FF#;
      Vendor  : constant Unsigned_32 := Mr1 and 16#1F#;
      Density : constant Unsigned_32 := Mr2 and 16#07#;
      Vcc     : constant Unsigned_32 := Shift_Right (Mr3, 6) and 1;
      Mbit    : Unsigned_32;
      L1 : constant String :=
        "[ada-free-boot] PSRAM: vendor=0x%02x density=0x%x %u Mbit Vcc(1=3v0)=%u"
        & ASCII.LF & ASCII.NUL;
      L2 : constant String :=
        "[ada-free-boot]   MR0=%02x MR1=%02x MR2=%02x MR3=%02x MR4=%02x MR8=%02x"
        & ASCII.LF & ASCII.NUL;
   begin
      case Density is
         when 16#1# => Mbit := 32;  S_Psram_Size := Shift_Left (Unsigned_32 (4), 20);
         when 16#3# => Mbit := 64;  S_Psram_Size := Shift_Left (Unsigned_32 (8), 20);
         when 16#5# => Mbit := 128; S_Psram_Size := Shift_Left (Unsigned_32 (16), 20);
         when 16#7# => Mbit := 256; S_Psram_Size := Shift_Left (Unsigned_32 (32), 20);
         when 16#6# => Mbit := 512; S_Psram_Size := Shift_Left (Unsigned_32 (64), 20);
         when others => Mbit := 0;  S_Psram_Size := 0;
      end case;
      Ign := P4 (L1'Address, Vendor, Density, Mbit, Vcc);
      Ign := P6 (L2'Address, Mr0, Mr1, Mr2, Mr3, Mr4, Mr8);
   end Report;

   function Impl_Enable return Integer is
      Mr : array (0 .. 1) of Unsigned_8 := (0, 0);
      Wr : aliased Unsigned_32 := 16#5A6B_7C8D#;
      Rd : aliased Unsigned_32 := 0;
      Fail : constant String :=
        "[ada-free-boot] PSRAM connect FAIL rd=0x%08x" & ASCII.LF & ASCII.NUL;
   begin
      --  pins (CS1 pad + SMEM clk drive), CS timing 3/3/2, ECC off.
      Poke (16#6000_906C#, 16#0000_0F00#);   --  IO_MUX GPIO26 -> SPICS1, FUN_DRV=3
      Poke (16#6000_33FC#, 16#0210_105F#);   --  SPI0 SPI_MEM_DATE
      Poke (16#6000_30DC#, 16#0400_B18F#);   --  SPI_MEM_SPI_SMEM_AC_REG(0)
      Poke (16#6002_6058#, Peek (16#6002_6058#) and not Shift_Left (Unsigned_32 (1), 8));

      Enter_Low_Speed;                       --  20 MHz for the MR transactions
      Poke (16#6000_20E0#, Peek (16#6000_20E0#) or 2);   --  SPI1 var-dummy
      Spi_Set_Dtr_Swap (1, 0, 0);

      --  MR0: read-modify-write low 6 bits -> 0x28 (lt=1, read_latency=2, drive=0).
      Opi_Exec (1, Opi_Dtr, 16#4040#, 16, 0, 32, 8,
                Null_Address, 0, Mr'Address, 16, Cs1, 0);
      Mr (0) := (Mr (0) and not 16#3F#) or 16#28#;
      Opi_Exec (1, Opi_Dtr, 16#C0C0#, 16, 0, 32, 0,
                Mr'Address, 16, Null_Address, 0, Cs1, 0);

      --  connectivity probe: write 0x5a6b7c8d, read back.
      Opi_Exec (1, Opi_Dtr, 16#8080#, 16, 0, 32, 8,
                Wr'Address, 32, Null_Address, 0, Cs1, 0);
      Opi_Exec (1, Opi_Dtr, 16#0000#, 16, 0, 32, 18,
                Null_Address, 0, Rd'Address, 32, Cs1, 0);
      if Rd /= Wr then
         Ign := P1 (Fail'Address, Rd);
         return -1;
      end if;

      Report;                                --  decode + print (still slow clock)
      Enter_High_Speed;                      --  80 MHz

      --  SPI0 cache OPI-DDR phases (golden, final state).
      Poke (16#6000_3044#, 16#007C_0000#);   --  SRAM_CMD : octal cmd/addr/data
      Poke (16#6000_3048#, 16#F000_0000#);   --  SRAM_DRD_CMD : read cmd 0x0000
      Poke (16#6000_304C#, 16#F000_8080#);   --  SRAM_DWR_CMD : write cmd 0x8080
      Poke (16#6000_30E4#, 16#0000_3023#);   --  SMEM_DDR : DDR en + var dummy
      Poke (16#6000_3040#, 16#01F7_C479#);   --  CACHE_SCTRL : usr cmd/addr/dummy/OCT
      Cache_Resume_DCache (0);
      return 0;
   end Impl_Enable;

   --  ---- 80 MHz din calibration (was psram_boot.c psram_tune_din) ----------
   --  3-bit sampling mode m replicated across the 9 din fields (8 data + DQS).
   function Din_Word (M : Unsigned_32) return Unsigned_32 is
      V : Unsigned_32 := 0;
      Mm : constant Unsigned_32 := M and 7;
   begin
      for I in 0 .. 8 loop
         V := V or Shift_Left (Mm, I * 3);
      end loop;
      return V;
   end Din_Word;

   procedure Tune_Din is
      Addr : constant Unsigned_32 := 16#001F_0000#;    --  PSRAM past the app's 1 MB
      Ref_V : constant Unsigned_32 := 16#A55A_1234#;
      Ref : aliased Unsigned_32 := Ref_V;
      Rd  : aliased Unsigned_32;
      Pass : Unsigned_32 := 0;
      Best : Unsigned_32 := 1;
      Run, Start, Best_Run : Unsigned_32 := 0;
      Msg : constant String :=
        "[ada-free-boot] PSRAM din tuned @80MHz: passmask=0x%02x -> mode %u"
        & ASCII.LF & ASCII.NUL;
   begin
      --  reference write (data-out, din-independent), then sweep the read din.
      Opi_Exec (1, 7, 16#8080#, 16, Addr, 32, 8, Ref'Address, 32, Null_Address, 0, 2, 0);
      for M in Unsigned_32 range 0 .. 7 loop
         Poke (Spi0_Smem_Din_Mode, Din_Word (M));
         Poke (Spi1_Smem_Din_Mode, Din_Word (M));
         Rd := 0;
         Opi_Exec (1, 7, 16#0000#, 16, Addr, 32, 18, Null_Address, 0, Rd'Address, 32, 2, 0);
         if Rd = Ref_V then
            Pass := Pass or Shift_Left (Unsigned_32 (1), Natural (M));
         end if;
      end loop;

      --  centre of the widest CIRCULAR run of passing modes (two laps catch a
      --  window wrapping the 7->0 seam); fall back to mode 1 if degenerate.
      if Pass /= 0 and then Pass /= 16#FF# then
         for I in 0 .. 15 loop
            declare
               Bit : constant Natural := I mod 8;
            begin
               if (Pass and Shift_Left (Unsigned_32 (1), Bit)) /= 0 then
                  if Run = 0 then
                     Start := Unsigned_32 (I);
                  end if;
                  Run := Run + 1;
                  if Run > Best_Run and then Run <= 8 then
                     Best_Run := Run;
                     Best := (Start + Run / 2) and 7;
                  end if;
               else
                  Run := 0;
               end if;
            end;
         end loop;
      end if;

      --  Prefer mode 1 whenever the SPI1 sweep shows it in-window.  Why not just
      --  trust the SPI1 centre: the sweep reads through SPI1's din, whose eye is
      --  WIDER than and offset from the cache's own SPI0 din eye.  Directly
      --  measured on the tight-eye board (a one-off async-preload cache probe, the
      --  only hang-safe way to read the SPI0 din path) the cache eye is {0,1}
      --  while SPI1 saw {0,1,6,7} -- so the SPI1 centre can land on a cache-BAD
      --  mode (6/7).  Mode 1 sits inside the *measured* cache eye on every octal
      --  chip tested.  That cache probe CANNOT run at every boot: a bad-din cache
      --  burst wedges the shared MSPI (SPI0 also serves flash XIP) with no
      --  recovery -- Cache_Disable itself then hangs -- so the SPI1 proxy plus
      --  this validated pick is the safe production path.  (See research
      --  PSRAM_BRINGUP_RESEARCH.md, "cache-din eye measurement".)
      if (Pass and Shift_Left (Unsigned_32 (1), 1)) /= 0 then
         Best := 1;
      end if;

      Poke (Spi0_Smem_Din_Mode, Din_Word (Best));   --  apply the chosen cache din
      Poke (Spi1_Smem_Din_Mode, 0);                 --  SPI1 din back to default
      Ign := P2 (Msg'Address, Pass, Best);
   end Tune_Din;

   --  ---- the bring-up entry (was psram_boot.c psram_bringup) ----------------
   procedure Bringup is
      Pages : constant Unsigned_32 := Unsigned_32 (Board_Cfg.Psram_Pages);
      Up  : constant String :=
        "[ada-free-boot] octal PSRAM up: rc=%d  %u MB" & ASCII.LF & ASCII.NUL;
      Mp  : constant String :=
        "[ada-free-boot] PSRAM mapped @0x3D000000 rc=%d" & ASCII.LF & ASCII.NUL;
      Prc : Integer;
      Mrc : Integer;
   begin
      --  octal MSPI pins (ROM leaves SPID4-7 + DQS unwired) + pad drive.
      Opi_Pin_Config;
      Set_Pin_Drive;

      Prc := Impl_Enable;
      Ign := P2 (Up'Address, Unsigned_32'Mod (Prc), Shift_Right (S_Psram_Size, 20));

      --  map Pages x 64 KB of PSRAM @0x3D000000 (size from board.ads).
      Cache_Disable_DCache;
      Mrc := Cache_Dbus_MMU_Set (16#8000#, 16#3D00_0000#, 0, 64, Pages, 0);
      Cache_Enable_DCache (0);
      Ign := P1 (Mp'Address, Unsigned_32'Mod (Mrc));

      --  measure + apply the 80 MHz cache-read din.
      Tune_Din;
   end Bringup;

end Boot_Psram;
